spring:
  application:
    name: dingdang-goods
  datasource:
    username: devuser
    password: 123456
    url: jdbc:mysql://localhost:3306/dingdang_goods
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

server:
  port: 8000

mybatis-plus:
  mapper_locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto



